# Generated by Django 5.0.6 on 2026-05-20 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('base', models.CharField(max_length=10)),
                ('quote', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.DecimalField(decimal_places=10, max_digits=24)),
                ('bid', models.DecimalField(decimal_places=10, max_digits=24)),
                ('ask', models.DecimalField(decimal_places=10, max_digits=24)),
                ('sources', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_prices', to='pricing.instrument')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['instrument', '-timestamp'], name='pricing_con_instrum_8e6fb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='OHLCBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', '1 minute'), ('5m', '5 minutes'), ('1h', '1 hour')], db_index=True, max_length=8)),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=10, max_digits=24)),
                ('high', models.DecimalField(decimal_places=10, max_digits=24)),
                ('low', models.DecimalField(decimal_places=10, max_digits=24)),
                ('close', models.DecimalField(decimal_places=10, max_digits=24)),
                ('volume', models.DecimalField(decimal_places=10, default=0, max_digits=24)),
                ('tick_count', models.PositiveIntegerField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc_bars', to='pricing.instrument')),
            ],
            options={
                'ordering': ('-bucket_start',),
                'indexes': [models.Index(fields=['instrument', 'interval', '-bucket_start'], name='pricing_ohl_instrum_a96601_idx')],
                'unique_together': {('instrument', 'interval', 'bucket_start')},
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase'), ('kraken', 'Kraken')], db_index=True, max_length=20)),
                ('bid', models.DecimalField(decimal_places=10, max_digits=24)),
                ('ask', models.DecimalField(decimal_places=10, max_digits=24)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='pricing.instrument')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['instrument', '-timestamp'], name='pricing_quo_instrum_3ee862_idx'), models.Index(fields=['source', '-timestamp'], name='pricing_quo_source_a56313_idx')],
            },
        ),
    ]
