# Generated by Django 5.0.6 on 2026-05-20 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_venue', models.CharField(max_length=20)),
                ('buy_price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('sell_venue', models.CharField(max_length=20)),
                ('sell_price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('spread', models.DecimalField(decimal_places=10, max_digits=24)),
                ('spread_bps', models.DecimalField(decimal_places=4, max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_opportunities', to='pricing.instrument')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['instrument', '-timestamp'], name='pricing_arb_instrum_1b3cb5_idx')],
            },
        ),
    ]
